### ISSUE TITLE
Location of postgresql

### ISSUE THREAD

**Issue by treaves** [vapor/cpostgresql#1]
This package presumes where postgresql is installed.  On Linux, this may be reasonable.  On Mac, it is not.

As I'm new to Swift and packages, I don't know how to address this.  But is there really no way to set the location in a more reasonable way, say like cmake, or autoconf does?

**Comment by tanner0101** [comment]
This is where the location of the lib on macOS is determined:

https://github.com/vapor/cpostgresql/blob/master/module.modulemap#L2

**Comment by treaves** [comment]
No, it is not determined there, it is set there.  As I said, the location in presumed.  ('it' being the location of the PostrgreSQL install)

I want to know if there is a way to determine the location, instead of presuming it.  Like cmake or autoconf do.

Thanks.
